#!/usr/bin/env bash
set -e

#### DB ####
export MYSQL_ROOT_PASSWORD=da642315cb2d390714590dad93e07c50
export MYSQL_DATABASE=shift
export MYSQL_USER=shift
export MYSQL_PASSWORD=ok124

export NGINX_HTTPS_PORT=4443
export NGINX_HTTP_PORT=4480
export NGINX_CERT_NAME=default
export NGINX_COMMON_NAME=localhost
export LETSENCRYPT_WEBROOT="/tmp/letsencrypt-auto"


#### DOCKER ####
export CONTAINERS="db nginx php hugo"
export COMPOSE_PROJECT_NAME="shift"

# Check for an overrides
if [ -f ${ROOT}/shift.overrides ]; then
    source ${ROOT}/shift.overrides
fi

#####
# === HERE BE DRAGONS ===
# These are some convenience pattens and functions that vincent@khougaz.com has found most helpful
# Feel free to copy into your own projects, or mostly don't worry about it!
#####

# ENV
export ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export SERVICES="${ROOT}/services"
export EVENTIMAGES="${ROOT}/legacy/eventimages"

SCRIPT_NAME=$(basename $0)

sub_help() { #                    - Show this text
    echo "Usage: ./${SCRIPT_NAME} <subcommand> [options]"
    echo "Subcommands:"
    # Extracts everything after "sub_" and outputs with the stuff after the comment
    cat ${ROOT}/shift | grep '^sub_.*#.*' | sed -E 's/sub_([a-z-]*).*#(.*)/    \1\2/'
}

sub_up() { #                      - Bring all services up
    sub_compose up -d ${CONTAINERS}
    echo "Run './${SCRIPT_NAME} watch' to monitor for changes and rebuild"
}

sub_watch() { #                   - Watch the site directory for changes and rebuild the site
    sub_compose run --rm hugo hugo -w
    wait
}

sub_down() { #                    - Stop and remove services
    sub_compose down
}

sub_ps() { #                      - Print service information
    sub_compose ps
}

sub_reload() { # <service>, ...   - Trigger a code/conf reload
    echo Reloading $@
    sub_compose kill -s SIGHUP $@
}

sub_start() { # <service>, ..     - Start service(s)
    sub_compose up -d $@
}

sub_stop() { # <service>, ...     - Stop service(s)
    sub_compose kill $@
}

sub_restart() { # <service>, ...  - Trigger entrypoint.sh, required after modifying anything in borzoi
    sub_stop $@
    sub_start $@
}

sub_rebuild() { # <service>, ...  - Remove and rebuild a service
    echo Rebuilding $@
    sub_stop $@
    sub_compose rm -f $@
    sub_compose up -d $@
}

sub_attach() { # <service>        - Run bash on a running service
    sub_compose exec $@ bash
}

sub_compose() { # <cmd...>        - Run a compose with associated files
    docker-compose $@
}

sub_logs() { # <service>, ...     - Show last 50 lines and attach to a service
    sub_compose logs --tail=50 -f $@
}

sub_mysql() { #                   - Open a mysql prompt with the db selected
    sub_compose exec db mysql -u ${MYSQL_USER} -h db -P 3306 -p"${MYSQL_PASSWORD}" ${MYSQL_DATABASE} $@
}

sub_mysql-pipe() { #              - Pipe sql into this command to send to db
    docker exec -i $(sub_compose ps -q db) mysql -u ${MYSQL_USER} -h db -P 3306 -p"${MYSQL_PASSWORD}" ${MYSQL_DATABASE} $@
}

sub_mysqldump() { #               - Dump the mysql database
    sub_compose exec db mysqldump -u ${MYSQL_USER} -h db -P 3306 -p"${MYSQL_PASSWORD}" ${MYSQL_DATABASE} $@
}

SUB_CMD=$1
case ${SUB_CMD} in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift

        set +e
        sub_${SUB_CMD} $@

        if [ $? = 127 ]; then
            echo "Error: '${SUB_CMD}' is not a known subcommand." >&2
            echo "       Run '${SCRIPT_NAME} --help' for a list of known subcommands." >&2
            exit 1
        fi
        set -e
        ;;
esac
