//
// Common values used by the calendar.
// see helpers.js for the client version. fix: how can we share?
//
const Shorthand = require('server/util/shorthand');

// example usage:
// Area.Portland.key = "P" - sent b/t client and server.
// Area.Portland.label = "Portland" - used for display and logging.
// Area.Portland.value = "Portland" - what it looks like in the database.
class Area {
  static Portland  = Shorthand.Enum('Portland');
  static Vancouver = Shorthand.Enum('Vancouver');
  static Westside  = Shorthand.Enum('Westside');
  static Eastside  = Shorthand.Enum('Eastside');
  static Clackamas = Shorthand.Enum('Clackamas');

  // ex. transform 'P' into "Portland"
  static keyToValue(key) { return Shorthand.keyToValue(Area, key) };
}

class Audience {
  static General = Shorthand.Enum('General', "General Audience");
  static Family  = Shorthand.Enum('Family');
  static Adult   = Shorthand.Enum('Adult');

  // ex. transform 'G' into "General"
  static keyToValue(key) { return Shorthand.keyToValue(Audience, key) };
}

// the status of a single instance of an event on a given day.
// generated by the daily_events view for backwards compatibility with existing queries.
class EventStatus {
  static Active    = new Shorthand('A', 'Active', 1);
  static Cancelled = new Shorthand('C', 'Cancelled', 0);

  // transform 'A' (active) into 1, and 'C' (cancelled) into 0
  // if neither, returns undefined
  static keyToValue(key) { return Shorthand.keyToValue(EventStatus, key) };
}

class Distance {
  // an array of common ride distances
  // example:
  // [0].key = "0-3"
  // [0].label = "0-3 miles"
  // [0].value = "0-3"
  static shorthands = [
    new Shorthand('0-3', '0-3 miles'),
    new Shorthand('3-8', '3-8 miles'),
    new Shorthand('8-15','8-15 miles'),
    new Shorthand('15+', '15+ miles'),
  ];

  // transforms '0-3' into '0-3'
  // returning undefined if the key was unknown.
  // ie. works as a validator
  static keyToValue(key) {
    const at = this.shorthands.findIndex(n => n.key === key);
    return at < 0 ? undefined : this.shorthands[at].value;
  }
}

class EventsRange {
  static MaxDays = 100;
}

class EventSearch {
  static Limit = 25;
}

// the loc_type of the location table
class LocType {
  static Start = 'start';
  static Finish = 'finish';
}

// Controls the sharing of organizer email, phone, and contact info.
class Showable {
  // can be shared freely online and in the print calendar.
  static Public    = new Shorthand('public');
  // should not be visible online nor printable in the calendar.
  static Private   = new Shorthand('private');
  // can be seen online.
  static Visible   = new Shorthand('visible');
  // can be printed in physical calendar.
  static Printable = new Shorthand('printable');

  static combine(visible, printable) {
    if (!visible && !printable) {
      return Showable.Private;
    } else if (visible && printable) {
      return Showable.Public;
    } else if (visible) {
      return Showable.Visible;
    } else if (printable) {
      return Showable.Printable;
    }
  };
}

// the tag_type of the tag table
class TagName {
  static Area       = 'area';
  static Audience   = 'audience';
  static Distance   = 'distance';
  static Featured   = 'featured';
  static LoopRide   = 'loopride'; // note= 'loop' is a reserved mysql word
  static SafetyPlan = 'safety';
}

// the web_type of the web table
class WebType {
  static Url = 'url';
}

//
module.exports = {
  Area,
  Audience,
  Distance,
  EventsRange,
  EventSearch,
  EventStatus,
  LocType,
  Showable,
  TagName,
  WebType,
};
