// CalEvent.review enum.
// see helpers.js for the authoritative version.
// fix: how can we share? symlink? some sort of copy by hugo build? remote fetch and make the api server authoritative??

const Area = Object.freeze({
  Portland : makeEnum('Portland'),
  Vancouver: makeEnum('Vancouver'),
  Westside : makeEnum('Westside'),
  Eastside : makeEnum('Eastside'),
  Clackamas: makeEnum('Clackamas'),
});

const Audience = Object.freeze({
  General : makeEnum('General', "General Audience"),
  Family  : makeEnum('Family'),
  Adult   : makeEnum('Adult'),
});

// the status of a single instance of an event on a given day.
// generated by the daily_events view for backwards compatibility with existing queries.
const EventStatus = Object.freeze({
  Active    : makeShorthand('A', 'Active', 1),
  Cancelled : makeShorthand('C', 'Cancelled', 0),   // explicitly cancelled by the owner.
  Delisted  : makeShorthand('D', 'Delisted', null), // the day has been removed without being explicitly cancelled.
  Skipped   : 'S', // a legacy value
});

// deprecated: CalEvent.review enum. here for migration.
const Review = Object.freeze({
  Inspect   : 'I',
  Excluded  : 'E', // legacy; reused for "soft deleting" already published events.
  Approved  : 'A',
  SentEmail : 'S',
  Revised   : 'R',
});

const Distance = [
  makeShorthand('0-3', '0-3 miles'),
  makeShorthand('3-8', '3-8 miles'),
  makeShorthand('8-15','8-15 miles'),
  makeShorthand('15+', '15+ miles'),
];

const EventsRange = Object.freeze({
  MaxDays : 100,
});

const EventSearch = Object.freeze({
  Limit : 25,
});

// the loc_type of the location table
const LocType = Object.freeze({
  Start: 'start',
  Finish: 'finish'
});

// the tag_type of the tag table
const TagName = Object.freeze({
  Area       : 'area',
  Audience   : 'audience',
  Distance   : 'distance',
  Featured   : 'featured',
  LoopRide   : 'loopride', // note: 'loop' is a reserved mysql word
  SafetyPlan : 'safety',
});

// the web_type of the web table
const WebType = Object.freeze({
  Url : 'url',
});

//
module.exports = {
  Area,
  Audience,
  EventSearch,
  EventsRange,
  EventStatus,
  LocType,
  Review,
  Distance,
  TagName,
  WebType,
};

// the name gets stored directly in the db.
// the first letter gets used as the shorthand key.
// ex. "P", and "Portland"
function makeEnum(name, label) {
  return makeShorthand(name[0], label || name, name);
}

function makeShorthand(key, label, data) {
  return {
    // the shorthand value sent b/t client and server.
    // the key was stored directly in the old db tables
    key,
    // human friendly display name
    label,
    // how it appears in the db:
    // the key if nothing specific requested
    // ex. enums get stored as their full name: ex. "Portland"
    // ridelength gets stored as the shorthand key: ex. "0-3"
    data: data !== undefined ? data : key,
  };
 }
