// CalEvent.review enum.
// see helpers.js for the authoritative version.
// fix: how can we share? symlink? some sort of copy by hugo build? remote fetch and make the api server authoritative??

// helper for the constants 
class Shorthand {
  // key: sent b/t client and server.
  // label: human friendly display name
  // value: how it appears in the db
  constructor(key, label, value) {
    this.key = key;
    this.label = label;
    this.value = value;
  }
  toString() {
    return this.key;
  }
}

// example usage:
// Area.Portland.key = "P" - sent b/t client and server.
// Area.Portland.label = "Portland" - used for display and logging.
// Area.Portland.value = "Portland" - what it looks like in the database.
class Area {
  static Portland  = makeEnum('Portland');
  static Vancouver = makeEnum('Vancouver');
  static Westside  = makeEnum('Westside');
  static Eastside  = makeEnum('Eastside');
  static Clackamas = makeEnum('Clackamas');

  // ex. transform 'P' into "Portland"
  static keyToValue(key) { return keyToValue(Area, key) };
}

class Audience {
  static General = makeEnum('General', "General Audience");
  static Family  = makeEnum('Family');
  static Adult   = makeEnum('Adult');

  // ex. transform 'G' into "General"
  static keyToValue(key) { return keyToValue(Audience, key) };
}

// the status of a single instance of an event on a given day.
// generated by the daily_events view for backwards compatibility with existing queries.
class EventStatus {
  static Active    = makeShorthand('A', 'Active', 1);
  static Cancelled = makeShorthand('C', 'Cancelled', 0);

  // transform 'A' (active) into 1, and 'C' (cancelled) into 0
  // if neither, returns undefined
  static keyToValue(key) { return keyToValue(EventStatus, key) };
}

class Distance {
  // an array of common ride distances
  // example:
  // [0].key = "0-3"
  // [0].label = "0-3 miles"
  // [0].value = "0-3"
  static shorthands = [
    makeShorthand('0-3', '0-3 miles'),
    makeShorthand('3-8', '3-8 miles'),
    makeShorthand('8-15','8-15 miles'),
    makeShorthand('15+', '15+ miles'),
  ];

  // transforms '0-3' into '0-3'
  // returning undefined if the key was unknown.
  // ie. works as a validator
  static keyToValue(key) {
    const at = this.shorthands.findIndex(n => n.key === key);
    return at < 0 ? undefined : this.shorthands[at].value;
  }
}

class EventsRange {
  static MaxDays = 100;
}

class EventSearch {
  static Limit = 25;
}

// the loc_type of the location table
class LocType {
  static Start = 'start';
  static Finish = 'finish';
}

// the tag_type of the tag table
class TagName {
  static Area       = 'area';
  static Audience   = 'audience';
  static Distance   = 'distance';
  static Featured   = 'featured';
  static LoopRide   = 'loopride'; // note= 'loop' is a reserved mysql word
  static SafetyPlan = 'safety';
}

// the web_type of the web table
class WebType {
  static Url = 'url';
}

//
module.exports = {
  Area,
  Audience,
  EventSearch,
  EventsRange,
  EventStatus,
  LocType,
  Distance,
  TagName,
  WebType,
};

// the name gets stored directly in the db.
// the first letter gets used as the shorthand key.
// ex. "P", and "Portland"
function makeEnum(name, label) {
  return new Shorthand(name[0], label || name, name);
}

function makeShorthand(key, label, value) {
  return new Shorthand(key,label, value !== undefined ? value : key);
}

function keyToValue(cls, key) {
  for (const name in cls) {
    const short = cls[name]
    if (short.key === key) {
      return short.value;
    }
  }
}
