const views = require("./views");

// used to create tables
const tableStatements = {
  image: imageTable,
  location: locationTable,
  print: printTable,
  private: privateTable,
  schedule: scheduleTable,
  series: seriesTable,
  tag: tagTable,
  web: webTable,
};

// certain tables have extra keys
// todo: a nicer way to handle this?
const extraKeys = {
  location: "loc_type",
  tag: "tag_type",
  web: "web_type",
};

// create tables if they dont already exist
// fix? modified time doesn't work for sqlite
// ( maybe manually set the time in knex.js store()? )
module.exports = {

  // 'image', 'series', etc.
  tableNames: Object.keys(tableStatements),

  dumpTableStatements(db) {
    return dumpTableStatements(db.query, db.config.type === 'mysql');
  },

  createTables(db, {drop}) {
    if (!db.config.type) {
      throw new Error(`missing db type`);
    }
    return createAll(db.query, db.config.type === 'mysql', drop)
  },

  // adds new event data to the db, promising the generated seriesId.
  //   eventData is a map of tableName => tableData
  //   the tableData can be one row of data, or multiple rows ( an array. )
  //   each row of data is an object { column_name: column_data }.
  // NOTE: this doesn't do any data validation nor any secret testing.
  insertEventData(tx, eventData) {
    // first: insert the series table first
    return tx('series').insert(eventData.series).then(row => {
      // the series id is autogenerated by the series table
      const seriesId = row[0];
      // then: insert the other tables
      // get all those table names
      const otherTables = Object.keys(eventData).filter(tableName => tableName !== 'series');
      // visit all of them, insert returns a promise
      // make a list of all the promised inserts
      const promises = otherTables.flatMap(tableName => {
        // concat normalizes one or more rows in the data to a list of rows.
        const rows = [].concat(eventData[tableName]).filter(rowData => {
          // filter out any empty rows out of the inserted data.
          return !isEmptyRow(tableName, rowData);
        });
        return rows.map(rowData => {
          rowData.id = seriesId; // every row in every table references the series
          return tx(tableName).insert(rowData);
        });
      });
      return Promise.all(promises).then(_ => seriesId);
    });
  },

  // issues statements to update rows ( or remove them if empty )
  // the eventData format matches the .insert() format ( above )
  // NOTE: this doesn't do any data validation nor any secret testing.
  updateEventData(tx, seriesId, eventData) {
    const updates = Object.keys(eventData).flatMap(tableName => {
      const vals = eventData[tableName];
      const rows = [].concat(vals); // normalize into an array
      return rows.map(rowData =>
        updateOrDelete(tx, tableName, seriesId, rowData));
    });
    return Promise.all(updates);
  },

  // exposed for testing:
  isEmptyRow,
};

function updateOrDelete(tx, tableName, seriesId, rowData) {
  const q =  tx(tableName).where('id', seriesId);
  const extraKey = extraKeys[tableName];
  if (extraKey) {
    q.where(extraKey, rowData[extraKey]);
  }
  // for safety, lets only try to delete rows from the special type tables
  if (extraKey && isEmptyData(rowData, [extraKey])) {
    q.del();
  } else {
    q.update(rowData);
  }
  return q;
};

// returns `true` if every value in the passed row data is empty
// where `tableName` is a known table, and `rowData` is a map of { column_name: column_data }.
// used by insertEventData() to skip inserting data which would generate a row of empty data.
// ( ex. a tag with a false value, or an empty ending location. )
function isEmptyRow(tableName, rowData) {
  const extraKey = extraKeys[tableName];
  return isEmptyData(rowData, ['id', extraKey]);
}

// helper for isEmptyRow
// if the named column isnt in the ignore list,
// and it has a non-zero value; the row has data.
function isEmptyData(rowData, ignore = []) {
  const first = Object.keys(rowData).findIndex(colName =>
    !ignore.includes(colName) && !!rowData[colName]);
  return first < 0;
}

function dumpTableStatements(knex, isMysql, drop) {
  const tableNames = Object.keys(tableStatements);
  const pairs = tableNames.map(name => {
    const q = knex.schema.createTable(name, (table) => {
      const make = newTableMaker(knex, isMysql, table);
      const cb = tableStatements[name];
      cb(make, table);
    });
    return [name, q.toSQL()[0].sql];
  });
  return new Map(pairs);
}

async function createAll(knex, isMysql, drop) {
  const tableNames = Object.keys(tableStatements);
  const drops = drop ? Promise.all(tableNames.map(n => knex.schema.dropTableIfExists(n)))
                : Promise.resolve(true);
  await drops;
  for (const name of tableNames) {
    const exists = await knex.schema.hasTable(name);
    if (!exists) {
      await knex.schema.createTable(name, (table) => {
        const make = newTableMaker(knex, isMysql, table);
        const cb = tableStatements[name];
        cb(make, table);
      });
    }
  }
  // helper function for views:
  async function makeView(name, raw) {
    await knex.schema.dropViewIfExists(name);
    await knex.schema.createView(name, (view) => {
      return view.as(knex.raw(raw));
    });
  }
  for (const name in views) {
    await makeView(name, views[name]);
  }
  // auto-increments the 'published' column of series
  // whenever data in series get updated.
  // the trigger will get dropped whenever the series table is dropped.
  await knex.schema.raw(`
    create trigger if not exists increment_published
    after update on series
    for each row
    begin
      update series
      set published = old.published + 1
      where series.id = old.id and old.published is not null;
    end`);
}

// make is a tableMaker
function seriesTable(make) {
  make.primaryKey('id');
  make.integer('published'); // a counter of the number of times published
  make.string('title', {width: 256});
  make.string('tiny', {width: 50});
  make.string('organizer', {width: 256});
  make.string('start_time', {width: 10, required: true});
  make.integer('ride_duration'); // in minutes
  make.string('details', {width: 6500}); // there's a few in the 6k range
  make.createdTime();
  make.modifiedTime();
}
function imageTable(make) {
  make.dependentKey('id');
  make.integer('img_version');  // often null for old data where there is no version number.
  make.string('img_ext', {width: 8}); // ex. "png" (lowercase, no leading dot)
  make.string('img_override', {width: 64});
  // make.string('img_alt', 512); -- future
}
function locationTable(make) {
  make.dependentKey('id','loc_type');
  make.string('loc_type', {width: 32, required: true});
  make.string('place_name', {width: 256});
  make.string('address', {width: 256});
  make.string('place_info', {width: 256});
  make.string('time_info', {width: 256});
}
function printTable(make) {
  make.dependentKey('id');
  // make.boolflag('no_print'); -- a way to opt out?
  make.boolflag('add_email');    // 'add' to help indicate its a boolean
  make.boolflag('add_phone');    // unlike 'printed_summary' which is text.
  make.boolflag('add_link');
  make.boolflag('add_contact');
  make.string('printed_summary', {width: 812}); // was: printdescr
}
function privateTable(make) {
  make.dependentKey('id');
  make.string('secret', {width: 48});    // passwords are generally 33 chars (32 plus the null terminator. ) max 48 here for ... padding?
  make.string('private_email', {width: 64});
  make.string('private_phone', {width: 64}); // some people have a short description here.
  make.string('private_contact',{width:  256});
  make.boolflag('show_email');
  make.boolflag('show_phone');
  make.boolflag('show_contact');
}
function scheduleTable(make) {
  // unfortunately, for backwards compat, pkid has to be the key
  // ( otherwise it'd be a dependentKey on id, ymd )
  make.integer('id', {required: true});
  make.string('ymd', {width: 12, required: true});
  // defaults to 0, and can be set to null
  make.boolflag('is_scheduled', {default: 0, required: false});
  // FIX! i would love to get rid of the pkid.
  // and replace it with queries like calendar/:series:/:yyyy-mm-dd:
  // we can change the web-client, but tbd on the ios bike fun app.
  make.primaryKey('pkid');
  // create/modified times for the scheduled days
  // uses different names than the series to avoid query conflicts
  make.createdTime('added');
  make.modifiedTime('changed');
  make.string('news', {width: 1024});
  // ideally this would be the primary key:
  make.uniqueIndex('id', 'ymd');
}
function tagTable(make) {
  make.dependentKey('id','tag_type');
  make.string('tag_type', {width: 32, required: true});
  make.string('tag_value', {width: 128, required: true});
}
function webTable(make) {
  make.dependentKey('id','web_type');
  make.string('web_type', {width: 32, required: true});
  make.string('web_text', {width: 256});
  make.string('web_link', {width: 512});
}

// wrapper to provide a simpler version of creating tables.
function newTableMaker(knex, isMysql, table) {
  if (isMysql) {
    table.engine("MyISAM");
  }
  return {
    primaryKey(name) {
      // knex creates these as unsigned; the original tables were signed
      // it should be fine; that's a lot of ids.
      // knex uses this as the primary key if another isn't specified.
      table.increments(name);
    },
    // a column to reference the series
    // with no compositeKey,
    //  the series id alone uniquely identifies the row.
    // with a compositeKey,
    //  the series id and the named column together uniquely identify the row.
    dependentKey(id, compositeKey = false) {
      const column = table.integer(id).notNullable();
      if (!compositeKey) {
        column.primary();
      } else {
        table.primary([id, compositeKey]);
      }
    },
    uniqueIndex(...columns) {
      return table.index(columns);
    },
    // add a column for row created time
    createdTime(name = 'created') {
      table.timestamp(name)
      .notNullable()
      .defaultTo(knex.fn.now());
    },
    // add a column for row modified time
    // fix? modified time doesn't work for sqlite;
    // ( maybe manually set the time in knex.js store()? )
    modifiedTime(name = 'modified') {
      const ts= table.timestamp(name).notNullable();
      if (!isMysql) {
        ts.defaultTo(knex.fn.now());
      } else {
        ts.defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
      }
    },
    // a 0/1 flag that defaults to 0
    boolflag(name, opt = {default: 0, required: true}) {
      const column = table.tinyint(name, 1);
      setDefaults(column, opt);
    },
    // 4 byte signed value (-2147483648 to 2147483647)
    integer(name, opt = {default: 0, required: false}) {
      // note: in the original tables `int(11)` is a *display* size
      // and its deprecated as of mysql 8.0.17
      // https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html
      const column = table.integer(name);
      setDefaults(column, opt);
    },
    // a string containing no more than {'width'} characters.
    // not required ( can be null ) by default.
    string(name, opt) {
      const column = table.string(name, opt.width);
      setDefaults(column, opt);
    },
  };
}

// where opt can contain { required: <true/false>, default: <value> }
function setDefaults(column, opt) {
  if (opt.default !== undefined) {
    column.defaultTo(opt.default);
  }
  if (opt.required) {
    column.notNullable();
  }
}
